### ISSUE TITLE
The viewport option does't work on mobile

### ISSUE THREAD

**Issue by sniper1720** [abhibagul/Zune-Blogger-Template#1]
Hello
The desktop version is shown on mobile, instead of scaling to viewport.

**Comment by abhibagul** [comment]
#2 solved.

Thank you for informing, theme updated.

use the following meta for the viewport
&lt;meta content='width=device-width, initial-scale=1.0, user-scalable=yes' name='viewport'/>

**Comment by sniper1720** [comment]
Thanks you, the issue is fixed.
