### ISSUE TITLE
The code format is cutted off on blogger mobile view without a scrolling bar option.

### ISSUE THREAD

**Issue by sniper1720** [abhibagul/Zune-Blogger-Template#2]
The code format is cutted off on blogger mobile view without a scrolling bar option. This is my blog post with this inconvenient: My blog post.

**Comment by abhibagul** [comment]
Thank you for informing, theme updated.

use the following meta for the viewport
&lt;meta content='width=device-width, initial-scale=1.0, user-scalable=yes' name='viewport'/>
