### ISSUE TITLE
Remove Google Plus from template 

### ISSUE THREAD

**Issue by sniper1720** [abhibagul/Zune-Blogger-Template#3]
Hello
Thanks for this beautiful template.
As Google Plus is dead, it's should be removed from template code.

**Comment by abhibagul** [comment]
Already Zune has the feature to remove the google plus in the layout section.

**Comment by sniper1720** [comment]
Thanks for your reply, The google plus code should be removed from the template "xml" code to make it clean.

**Comment by abhibagul** [comment]
It is available in the layout section. Social sharing widget > remove google from the list.
