### ISSUE TITLE
Add more social media icons

### ISSUE THREAD

**Issue by sniper1720** [abhibagul/Zune-Blogger-Template#4]
Hi
I know that reporting bugs and features request is a must to improve software and codes,  so why not adding mastodon, telegram, minds... icons.

**Comment by abhibagul** [comment]
Already supported.

**Comment by sniper1720** [comment]
I can't add telegram or mastodon icons to social media layout and the documentation doesn't mention that too.

**Comment by abhibagul** [comment]
I see, add the following code just above the &lt;/head>

```
<style>
/*<![CDATA[*/
.bottom-bar-social .telegram:before{     content: "\f2c6" }
/*]]>*/
</style>
```

and use telegram to use it.

Whereas mastodon is not supported in FA 4.7
