### ISSUE TITLE
Show disqus comments count instead of blogger comments count 

### ISSUE THREAD

**Issue by sniper1720** [abhibagul/Zune-Blogger-Template#5]
Hello
As disqus is becoming more popular, why not offer an option to show disqus comment count instead of blogger comments count or a documentation about that. 
Thanks in advance.

**Comment by abhibagul** [comment]
Technical limitations.

**Comment by sniper1720** [comment]
So, buying a template or self modifying this one,  is the solution.

**Comment by abhibagul** [comment]
Yes
